<?php /** @var \Df\Config\DynamicTable\Column\SelectBlock $block */ ?>
<?php
	/** @var string $columnName */
	$columnName = df_ejs($block->getColumn()->getName());
	/** синтаксис шаблонов Prototype: http://api.prototypejs.org/language/Template/ */
?>
<script type='text/javascript'>
	(function($) {$(function() {
		var $row = $(document.getElementById('#{_id}'));
		var $select = $('.<?php echo $columnName; ?>', $row);
		$select.val('#{<?php echo $columnName; ?>}');
		$select.select2(<?php echo df_ejs($block->getRenderOptions()); ?>);
	});})(jQuery);
</script>