<?php
/**
 * 2016-07-29
 * 2017-03-25
 * Изначально (2016-07-29) я использовал этот шаблон только для административного интерфейса:
 * он добавлял мой дополнительный класс CSS к таблице по сравнению со стандартным шаблоном.
 * Теперь же стандартный шаблон перестал меня устраивать и для витрины,
 * и я теперь намерен использовать (после предстоящего рефакторинга)
 * этот шаблон как для витрины, так и для административной части.
 * @var \Df\Payment\Block\Info $block
 */
echo $block->escapeHtml($block->getMethod()->getTitle());
/** @var array(string => string) $info */
if ($info = $block->getSpecificInformation()) {
	/** @var string $cssClass */
	$cssClass = df_cc_s('data-table admin__table-secondary df-payment-info', $block->ii('method'));
	echo df_tag('table', $cssClass, df_cc_n(df_map_k($info,
		/**
		 * @param string $label
		 * @param string $value
		 * @return string
		 */
		function($label, $value) use($block) {return
			df_tag('tr', [], df_cc_n(
				df_tag('th', [], $label)
				,df_tag('td', [], nl2br(df_cc_n($block->getValueAsArray($value, true))))
			))
		;}
	)));
}
echo $block->getChildHtml();
