<?php
/**
 * 2016-07-29
 * Перекрыл стандартный шаблон, чтобы добавить своё класс CSS к таблице.
 * @var \Df\Payment\Block\ConfigurableInfo $block
 */
echo $block->escapeHtml($block->getMethod()->getTitle());
/** @var array(string => string) $info */
$info = $block->getSpecificInformation();
if ($info) {
	/** @var string $cssClass */
	$cssClass = df_cc_s('data-table admin__table-secondary df-payment-info', $block->ii('method'));
	echo df_tag('table', $cssClass, df_cc_n(df_map_k($info,
		/**
		 * @param string $label
		 * @param string $value
		 * @return string
		 */
		function($label, $value) use($block) {
			return df_tag('tr', [], df_cc_n(
				df_tag('th', [], $label)
				,df_tag('td', [], nl2br(df_cc_n($block->getValueAsArray($value, true))))
			));
		}
	)));
}
echo $block->getChildHtml();
